config/routes.rb
Rails.application.routes.draw do
	root 'pages#home'

  get '/home', to: 'pages#home'
  get '/browser_extensions', to: 'pages#browser_extensions'
  get '/api', to: 'pages#api'
  get '/about', to: 'pages#about'

  resources :suggests, only: [:index, :create]
  resources :joins, only: [:index, :create]

  get 'api/v1/all'
  get 'api/v1/codeforces'
  get 'api/v1/codeforces_gym'
  get 'api/v1/top_coder'
  get 'api/v1/at_coder'
  get 'api/v1/cs_academy'
  get 'api/v1/code_chef'
  get 'api/v1/hacker_rank'
  get 'api/v1/hacker_earth'
  # get 'api/v1/kick_start'
  get 'api/v1/leet_code'
  get 'api/v1/sites'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/all.rb
class All < ApplicationRecord
  self.pluralize_table_names = false
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/at_coder.rb
class AtCoder < ApplicationRecord
  self.pluralize_table_names = false
end

app/models/code_chef.rb
class CodeChef < ApplicationRecord
  self.pluralize_table_names = false
end

app/models/codeforces.rb
class Codeforces < ApplicationRecord
end

app/models/codeforces_gym.rb
class CodeforcesGym < ApplicationRecord
  self.pluralize_table_names = false
end

app/models/cs_academy.rb
class CsAcademy < ApplicationRecord
  self.pluralize_table_names = false
end

app/models/hacker_earth.rb
class HackerEarth < ApplicationRecord
  self.pluralize_table_names = false
end

app/models/hacker_rank.rb
class HackerRank < ApplicationRecord
  self.pluralize_table_names = false
end

app/models/join.rb
class Join < ApplicationRecord
  include Orderability

  validates_presence_of :name
  validates_presence_of :email
  validates_presence_of :how

  validates_length_of :name, maximum: 255
  validates_length_of :email, maximum: 255
  validates_length_of :how, maximum: 5000

  validates_email_format_of :email
end

app/models/kick_start.rb
class KickStart < ApplicationRecord
  self.pluralize_table_names = false
end

app/models/last_update.rb
class LastUpdate < ApplicationRecord
end

app/models/leet_code.rb
class LeetCode < ApplicationRecord
  self.pluralize_table_names = false
end

app/models/suggest.rb
class Suggest < ApplicationRecord
  include Orderability

  validates_presence_of :site

  validates :site, url: true

  validates_length_of :site, maximum: 255
  validates_length_of :email, maximum: 255
  validates_length_of :message, maximum: 5000

  validates_email_format_of :email, allow_blank: true
end

app/models/top_coder.rb
class TopCoder < ApplicationRecord
  self.pluralize_table_names = false
end

app/models/toph.rb
class Toph < ApplicationRecord
	self.pluralize_table_names = false
end

app/helpers/emoji_helper.rb
module EmojiHelper
  def emojify(content, **options)
    Twemoji.parse(h(content), options).html_safe if content.present?
  end
end

app/helpers/joins_helper.rb
module JoinsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/suggests_helper.rb
module SuggestsHelper
end

app/views/layouts/_footer.html.erb
<footer id="footer" class="mt-4">
  <div class="container-fluid">
    <div class="row justify-content-center text-center text-lg-left">
      <div class="col-12 col-lg-11">
        <span>KONTESTS &copy; Copyright 2018-<%= Time.now.year %> <%= link_to('AliOsm', 'https://fb.com/AliOsm97', target: :_blank) %> All Rights Reserved</span>
        <br>
        <span class="text-muted">Designed and built with all the &nbsp;<span class="heart"><%= emojify(':heart:') %></span>&nbsp; in the world</span>
      </div>
    </div>
  </div>
</footer>

app/views/layouts/_head.html.erb
<title>KONTESTS</title>
<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta http-equiv="Expires" content="0">
<meta http-equiv="Content-Script-Type" content="text/javascript">
<meta http-equiv="Content-Style-Type" content="text/css">

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<meta name="description" content="Competitive programming contests schedule">
<meta name="keywords" content="competitive programming,problem solving,codeforces,csacademy,atcoder,codechef,a2oj,hacherearth">
<meta name="Distribution" content="Global">
<meta name="author" content="Ali Fadel">
<meta name="copyright" content="Ali Fadel 2018">
<meta name="robots" content="index,follow">
<meta name="revisit-after" content="1 days">
<meta name="contact" content="aliosm1997@gmail.com">
<meta name="generator" content="Sublime Text">
<meta name="language" content="English">
<meta name="rating" content="general">
<meta name="web_author" content="Ali Fadel">

<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

<%= favicon_link_tag 'logo.png' %>

<%= analytics_init if GoogleAnalytics.valid_tracker? %>

app/views/layouts/_messages.html.erb
<div class="row justify-content-center">
	<div class="col-12 col-lg-10">
		<% flash.each do |type, message| %>
		  <div class="my-5 alert alert-<%= type == 'alert' ? 'danger' : 'primary' %> fade-in">
		    <%= message %>

		    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
		      <span aria-hidden="true">&times;</span>
		    </button>
		  </div>
		<% end %>
	</div>
</div>

app/views/layouts/_navbar.html.erb
<header>
  <nav id="topNavbar" class="navbar navbar-expand-md fixed-top default-theme">
    <div class="container-fluid">
      <%= link_to(root_path, class: 'navbar-brand') do %>
        <%= image_tag('logo.svg', class: 'img-fluid', width: '36', onerror: "this.onerror=null; this.src='logo.png'") %> <span class="align-middle">KONTESTS</span>
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item <%= 'active' if action_name == 'about' %>">
            <%= link_to(about_path, class: 'nav-link') do %>
              <%= icon('fas', 'info-circle', 'About Kontests') %>
            <% end %>
          </li>
          <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              <%= icon('fas', 'life-ring', 'Supported Sites') %>
            </a>

            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
              <% SITES.each_with_index do |site, i| %>
                <% next if i.zero? %>
                <%= link_to(site.first, site.third, class: 'dropdown-item', target: :_blank) %>
              <% end %>
              <div class="dropdown-divider"></div>
              <button type="button" class="dropdown-item" data-toggle="modal" data-target="#suggestSite">
                Suggest site?
              </button>
            </div>
          </li>

          <li class="nav-item <%= 'active' if action_name == 'browser_extensions' %>">
            <%= link_to(browser_extensions_path, class: 'nav-link') do %>
              <%= icon('fas', 'puzzle-piece', 'Download Browser Extensions') %>
            <% end %>
          </li>

          <li class="nav-item <%= 'active' if action_name == 'api' %>">
            <%= link_to(api_path, class: 'nav-link') do %>
              <%= icon('fas', 'database', 'Free API For Developers!') %>
            <% end %>
          </li>
        </ul>
        <div class="ml-auto text-muted">
        <span title="Light mode">
          <%= icon('fa', 'sun') %>
        </span>
            <div class="custom-control custom-switch d-inline">
              <input type="checkbox" <%= theme.eql?('dark') ? 'checked' : '' %> class="custom-control-input" id="darkModeSwitch">
              <label class="custom-control-label" for="darkModeSwitch"></label>
            </div>
            <span title="Dark mode">
              <%= icon('fas', 'moon') %>
            </span>
        </div>
      </div>
    </div>
  </nav>
</header>

app/views/layouts/_suggest_site_modal.html.erb
<div class="modal fade" id="suggestSite" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content primary-dynamic-bg">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">We love your suggestions!</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body">
        <%= simple_form_for(@suggest) do |f| %>
				  <%= f.input :site, required: true, autofocus: true, placeholder: 'http://site.com', input_html: { maxlength: 255 } %>
          <%= f.input :email, placeholder: 'someone@somewhere.com', input_html: { maxlength: 255, type: :email } %>
          <%= f.input :message, placeholder: 'Tell us what we don\'t know!', input_html: { maxlength: 5000 } %>
				<% end %>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button id="submit_suggest" type="button" class="btn btn-primary">Submit</button>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <%= render 'layouts/head' %>
  </head>

  <body class="default-theme <%= theme %>-theme">
    <%= render 'layouts/suggest_site_modal' %>
    <%= render 'layouts/navbar' %>

    <div id="content">
      <div class="container-fluid">
        <%= render 'layouts/messages' %>
        <%= yield %>
      </div>
    </div>

    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/_join_team_modal.html.erb
<div class="modal fade" id="joinTeam" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content primary-dynamic-bg">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Hurry up, we need your skills!</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>

      <div class="modal-body">
        <%= simple_form_for(@join) do |f| %>
          <%= f.input :name, required: true, autofocus: true, placeholder: 'Your name', input_html: { maxlength: 255 } %>
          <%= f.input :email, placeholder: 'someone@somewhere.com', input_html: { maxlength: 255, type: :email } %>
          <%= f.input :how, label: 'How you can help?', placeholder: 'Tell us how you can help', input_html: { maxlength: 5000 } %>
        <% end %>
      </div>

      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button id="submit_join" type="button" class="btn btn-primary">Submit</button>
      </div>
    </div>
  </div>
</div>

app/views/pages/_show_contests.html.erb
<div class="<%= type %> primary-dynamic-bg px-3 py-4 shadow-sm rounded h-100 lazyLoader">
  <% if contests.blank? %>
    <p class="lead text-center font-weight-bold">0 <%= type.capitalize %> Contests</p>
    <hr/>
    <p class="alert alert-warning"><%= icon('fas', 'info-circle') %> There are no <%= type %> contests <%= emojify(emoji) %></p>
  <% else %>
    <p class="lead text-center font-weight-bold"><%= [contests.size, type.capitalize, 'Contest'.pluralize(contests.size)].join(' ') %></p>
    <hr/>
    <div class="table-responsive py-2 dark-scrollbar">
      <table class="table table-borderless table-hover table-striped border dataTable">
        <thead class="border-top border-bottom">
          <tr>
            <% contests.column_names.each do |column_name| %>
              <% next if column_name.eql?('url') %>
              <% next if ['url', 'owner_url', 'in_24_hours', 'status'].include? column_name %>

              <th scope="col">
                <%= column_name.tr('_', ' ').capitalize %>
              </th>
            <% end %>
          </tr>
        </thead>

        <tbody>
          <% contests.each do |contest| %>
            <tr class="<%= 'in-24-hours' if type == 'future' && contest[:in_24_hours] == 'Yes' %>">
              <% contests.column_names.each do |column_name| %>
                <% next if ['url', 'owner_url', 'in_24_hours', 'status'].include? column_name %>

                <td>
                  <% if column_name.eql? 'name' %>
                    <% unless contest['status'] == 'CODING' %>
                      <a class="add-to-calendar btn btn-light btn-sm py-0 px-1" data-toggle="tooltip" data-placement="top" title="Add to Calendar" target="_blank" href="https://calendar.google.com/event?action=TEMPLATE&dates=<%= contest['start_time'] %>/<%= contest['end_time'] %>&text=<%= contest['name'] %>&location=<%= contest['url'] %>"><small><%= icon('far', 'calendar-alt', 'Reminder') %></small></a> &nbsp;
                    <% end %>
                    <%= link_to contest['name'], contest['url'], target: '_blank' %>
                  <% elsif column_name.include? 'time' %>
                    <time class="contest-time"><%= contest[column_name] %></time>
                  <% elsif column_name.eql? 'duration' %>
                    <time class="contest-duration"><%= contest[column_name] %></time>
                  <% elsif column_name.eql? 'owner_name' %>
                    <%= link_to contest['owner_name'], contest['owner_url'], target: '_blank' %>
                  <% else %>
                    <%= raw contest[column_name] %>
                  <% end %>
                </td>
              <% end %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  <% end %>
</div>

app/views/pages/_show_sites.html.erb
<div class="tab-pane fade <%= 'show active' if site_class == @site_class %>" id="pills-<%= site_class %>" role="tabpanel" aria-labelledby="pills-<%= site_class %>-tab">
  <div class="row">
    <div class="col-12 col-lg-12">
      <p class="text-center text-muted">
        <%= t(:last_update) %> <%= timeago_tag last_update, :nojs => true, date_only: false %>
      </p>
    </div>
    <div class="col-12 col-lg-6">
      <%= render partial: 'show_contests', locals: { contests: future_contests, type: 'future', emoji: ':worried:', site_class: site_class } %>
    </div>
    <div class="col-12 col-lg-6 mobile-mt-3">
      <%= render partial: 'show_contests', locals: { contests: running_contests, type: 'running', emoji: ':grinning:', site_class: site_class } %>
    </div>
  </div>
</div>

app/views/pages/about.html.erb
<%= render 'join_team_modal' %>

<div class="row justify-content-center mt-5">
  <div class="col-12 col-lg-10">
    <div class="card-deck">
      <div class="card mb-4 primary-dynamic-bg">
        <div class="card-header">
          <div class="container">
            <div class="row text-center">
              <div class="col">
                <div class="sec-title">
                  <h2>What is our service?</h2>
                  <h3>The simplest and the greatest</h3>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="card-body">
          <div class="container">
            <div class="row justify-content-center">
              <div class="col">
                <p class="card-text about-text-size">
                  We bring all running and future contests between your hands
                  <%= emojify(':open_hands::skin-tone-3:') %> from many
                  different online judges.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="card mb-4 primary-dynamic-bg">
        <div class="card-header">
          <div class="container">
            <div class="row text-center">
              <div class="col">
                <div class="sec-title">
                  <h2>Why we do this?</h2>
                  <h3>The world needs this</h3>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="card-body">
          <div class="container">
            <div class="row justify-content-center">
              <div class="col">
                <p class="card-text about-text-size">
                  We believe we can save your time <%= emojify(':clock1030:') %>
                  and let you touch <%= emojify(':point_left::skin-tone-3:') %>
                  the information from many different places, in one place.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="card mb-4 primary-dynamic-bg">
        <div class="card-header">
          <div class="container">
            <div class="row text-center">
              <div class="col">
                <div class="sec-title">
                  <h2>How we pay?</h2>
                  <h3>There is nothing for free</h3>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="card-body">
          <div class="container">
            <div class="row justify-content-center">
              <div class="col">
                <p class="card-text about-text-size">
                  Till now we are paying for the site from our money, but if you like (or love) this service you can donate <%= link_to('here', 'https://paypal.me/KONTESTS', target: :_blank) %>, to make it faster, better and allow us to provide more features <%= emojify(':relieved:') %>.
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row justify-content-center">
  <div class="col-12 col-lg-10">
    <div class="card mb-4 primary-dynamic-bg">
      <div class="card-header">
        <div class="container">
          <div class="row text-center">
            <div class="col">
              <div class="sec-title">
                <h2>Who are we?</h2>
                <h3>Humans <%= emojify(':stuck_out_tongue:') %></h3>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="card-body">
        <div class="container">
          <div class="row justify-content-center mb-3">
            <div class="col-12 col-md-4">
              <div class="our-team">
                <div class="pic">
                  <%= image_tag('team/ali_fadel.jpg', class: 'card-img img-fluid') %>
                </div>
                <div class="team-content">
                  <h3>Ali H. Fadel</h3>
                  <span class="post"></span>
                </div>
                <ul class="social">
                  <li><%= link_to(icon('fab', 'facebook fa-2x'), 'https://fb.com/aliosm97', target: :_blank) %></li>
                  <li><%= link_to(icon('fab', 'github-square fa-2x'), 'https://github.com/AliOsm', target: :_blank) %></li>
                  <li><%= mail_to('aliosm1997@gmail.com', icon('fas', 'envelope-square fa-2x')) %></li>
                </ul>
              </div>
            </div>

            <div class="col-12 col-md-4">
              <div class="our-team">
                <div class="pic">
                  <%= image_tag('team/ridah_labbar.jpg', class: 'card-img img-fluid') %>
                </div>
                <div class="team-content">
                  <h3>Ridah O. Labbar</h3>
                  <span class="post"></span>
                </div>
                <ul class="social">
                  <li><%= link_to(icon('fab', 'facebook fa-2x'), 'https://web.facebook.com/r.labbar', target: :_blank) %></li>
                  <li><%= link_to(icon('fab', 'github-square fa-2x'), 'https://github.com/ridaomar', target: :_blank) %></li>
                  <li><%= mail_to('ridalabbar@gmail.com', icon('fas', 'envelope-square fa-2x')) %></li>
                </ul>
              </div>
            </div>

            <div class="col-12 col-md-4">
              <div class="our-team">
                <div class="pic">
                  <%= image_tag('team/ibraheem_tuffaha.jpg', class: 'card-img img-fluid') %>
                </div>
                <div class="team-content">
                  <h3>Ibraheem Z. Tuffaha</h3>
                  <span class="post"></span>
                </div>
                <ul class="social">
                  <li><%= link_to(icon('fab', 'facebook fa-2x'), 'https://fb.com/ibrahim.tuffaha.7', target: :_blank) %></li>
                  <li><%= link_to(icon('fab', 'github-square fa-2x'), 'https://github.com/IbraheemTuffaha', target: :_blank) %></li>
                  <li><%= mail_to('bro.t.1996@gmail.com', icon('fas', 'envelope-square fa-2x')) %></li>
                </ul>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row justify-content-center">
  <div class="col-12 col-lg-10">
    <div class="card primary-dynamic-bg">
      <div class="card-header">
        <div class="container">
          <div class="row text-center">
            <div class="col">
              <div class="sec-title">
                <h2>Want to help?</h2>
                <h3>We appreciate it <%= emojify(':heart:') %></h3>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="card-body pt-5">
        <div class="container">
          <div class="row justify-content-center">
            <div class="col-12 col-md-4 mb-4">
              <button type="button" class="btn btn-primary btn-block" data-toggle="modal" data-target="#joinTeam">
                Join KONTESTS team now!
              </button>
            </div>

            <div class="col-12 col-md-4">
              <a class="btn btn-primary btn-block" href="https://github.com/AliOsm/kontests" target="_blank">Contribute on GitHub</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/browser_extensions.html.erb
<div class="row justify-content-center mb-4 mt-5">
  <div class="col-12 col-lg-10">
    <div class="card primary-dynamic-bg">
      <div class="card-header">
        <div class="container">
          <div class="row text-center">
            <div class="col">
              <div class="sec-title">
                <h2>Why browser extensions?</h2>
                <h3>Because we need them <%= emojify(':nerd_face:') %></h3>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="card-body">
        <div class="container">
          <div class="row justify-content-center mb-4">
            <div class="col">
              <p class="card-text about-text-size">
                Our vision for KONTESTS is to provide an easy & fast tool for programmers to access online contests information; therefore a one click popup browser extension accessing online judges contests schedule is a must.
              </p>

              <p class="card-text about-text-size">
                The extension was developed during the 12-hours <a href="https://localhackday.mlh.io/" target="_blank">Local Hack Day</a> 2018 hackathon.
              </p>
            </div>
          </div>

          <div class="row justify-content-center mb-3">
            <div class="col-12 col-md-4">
              <a class="btn btn-primary btn-block" href="https://github.com/AliOsm/kontests-browser-extension" target="_blank">Contribute on GitHub</a>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="row justify-content-center">
  <div class="col-12 col-lg-10">
    <div class="card-deck">
      <div class="card primary-dynamic-bg">
        <div class="card-header">
          <div class="container">
            <div class="row text-center">
              <div class="col">
                <div class="sec-title">
                  <h2>Google Chrome</h2>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="card-body">
          <div class="container">
            <div class="row justify-content-center">
              <div class="col">
                <p class="text-center mb-0">
                  <%= link_to('https://chrome.google.com/webstore/detail/kontests/agpdemlkalmmeenclchlajdcmbcacoea', target: :_blank, class: 'browser-extension') do %>
                    <%= icon('fab fa-9x', 'chrome') %>
                  <% end %>
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>

      <div class="card primary-dynamic-bg">
        <div class="card-header">
          <div class="container">
            <div class="row text-center">
              <div class="col">
                <div class="sec-title">
                  <h2>Mozilla FireFox</h2>
                </div>
              </div>
            </div>
          </div>
        </div>

        <div class="card-body">
          <div class="container">
            <div class="row justify-content-center">
              <div class="col">
                <p class="text-center mb-0">
                  <%= link_to('https://addons.mozilla.org/en-US/firefox/addon/kontests', target: :_blank, class: 'browser-extension') do %>
                    <%= icon('fab fa-9x', 'firefox') %>
                  <% end %>
                </p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<div id="sitesHolder" class="row justify-content-center primary-dynamic-bg rounded shadow-sm px-lg-5 px-3">
  <!-- <div class="col-12 col-lg-2">
    <small class="text-black-50 mb-lg-0 mb-4 mt-3 d-block text-center text-lg-left">Choose Your Favorite Website:</small>
  </div> -->
  <div class="col-12 col-lg-10 overflow-x-auto dark-scrollbar">
    <ul class="nav nav-pills center-pills mb-3 mx-auto width-max-content" id="pills-tab" role="tablist" aria-orientation="vertical">
      <% @sites.each do |site| %>
        <% if site.third.size + site.fourth.size > 0 %>
          <li class="nav-item" onclick="redirectUrl(this)">
            <a class="nav-link rounded-0 <%= 'active' if site.second == @site_class %>" id="pills-<%= site.second %>-tab" data-toggle="pill" href="#pills-<%= site.second %>" role="tab" aria-controls="pills-<%= site.second %>" aria-selected="true" data-site="<%= site.second %>">
              <%= site.first %> &nbsp;<span class="badge badge-pill badge-dark"><%= site.third.size + site.fourth.size %></span>
            </a>
          </li>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>

<div class="row justify-content-center">
  <div class="col-12 col-lg-11">
    <div class="card border-0 bg-transparent">
      <div class="card-body pt-0 pr-0 pb-0 pl-0">
        <div class="tab-content pt-3" id="pills-tabContent">
          <% @sites.each do |site| %>
          <%= render partial: 'show_sites', locals: { site_class: site.second, future_contests: site.third, running_contests: site.fourth, last_update: site.fifth } if site.third.size + site.fourth.size > 0 %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>